server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.130:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.25.128